<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Test Email</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .content {
            background-color: #ffffff;
            padding: 20px;
            border: 1px solid #dee2e6;
            border-radius: 5px;
        }
        .footer {
            margin-top: 20px;
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 5px;
            font-size: 12px;
            color: #6c757d;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🧪 Test Email</h1>
        <p>This is a test email from your Laravel application</p>
    </div>
    
    <div class="content">
        <h2>Hello!</h2>
        <p>{{ $testMessage }}</p>
        
        <h3>Email Details:</h3>
        <ul>
            <li><strong>Sent at:</strong> {{ $timestamp }}</li>
            <li><strong>Application:</strong> Laravel Hotel Booking System</li>
            <li><strong>Status:</strong> Test Mode</li>
        </ul>
        
        <p>If you received this email, it means your mail configuration is working correctly!</p>
    </div>
    
    <div class="footer">
        <p>This is an automated test email. Please do not reply to this message.</p>
        <p>Generated by Laravel Mail System</p>
    </div>
</body>
</html> 